### ISSUE TITLE
Restructure template component

### ISSUE THREAD

**Issue by Stef3st** [openscd/oscd-component#5]
Some things need to change in order to succesfully use the template:

- Releaseplease action needs to:
  -  Include build
  - Change publish to publish --access public
  - For deployment, credentials need to be set
- Folder structure is needed
  - demo/src/stories/test
- .eslintrc file needs to be added
- .npmignore file needs to be added
- "skipLibCheck": true needs to be added to tsconfig.json

**Comment by Sander3003** [comment]
Close it
